const OPERATION_FIELD_LIST = [
  {
    name: "account_create",
    fields: [
      "fee",
      "creator",
      "new_account_name",
      "owner",
      "active",
      "posting",
      "memo_key",
      "json_metadata",
    ],
  },
  {
    name: "account_create_with_delegation",
    fields: [
      "fee",
      "delegation",
      "creator",
      "new_account_name",
      "owner",
      "active",
      "posting",
      "memo_key",
      "json_metadata",
      "extensions",
    ],
  },
  {
    name: "account_update",
    fields: [
      "account",
      "owner",
      "active",
      "posting",
      "memo_key",
      "json_metadata",
    ],
  },
  { name: "account_witness_proxy", fields: ["account", "proxy"] },
  {
    name: "account_witness_vote",
    fields: ["account", "witness", "approve"],
  },
  {
    name: "cancel_transfer_from_savings",
    fields: ["from", "request_id"],
  },
  {
    name: "change_recovery_account",
    fields: ["account_to_recover", "new_recovery_account", "extensions"],
  },
  {
    name: "claim_reward_balance",
    fields: ["account", "reward_hive", "reward_hbd", "reward_vests"],
  },
  { name: "claim_account", fields: ["creator", "fee", "extensions"] },
  {
    name: "comment",
    fields: [
      "parent_author",
      "parent_permlink",
      "author",
      "permlink",
      "title",
      "body",
      "json_metadata",
    ],
  },
  {
    name: "comment_options",
    fields: [
      "author",
      "permlink",
      "max_accepted_payout",
      "percent_hbd",
      "allow_votes",
      "allow_curation_rewards",
      "extensions",
    ],
  },
  { name: "convert", fields: ["owner", "requestid", "amount"] },
  {
    name: "create_claimed_account",
    fields: [
      "creator",
      "new_account_name",
      "owner",
      "active",
      "posting",
      "memo_key",
      "json_metadata",
      "extensions",
    ],
  },
  { name: "custom", fields: ["required_auths", "id", "data"] },
  {
    name: "custom_binary",
    fields: [
      "required_owner_auths",
      "required_active_auths",
      "required_posting_auths",
      "required_auths",
      "id",
      "data",
    ],
  },
  {
    name: "custom_json",
    fields: ["required_auths", "required_posting_auths", "id", "json"],
  },
  { name: "decline_voting_rights", fields: ["account", "decline"] },
  {
    name: "delegate_vesting_shares",
    fields: ["delegator", "delegatee", "vesting_shares"],
  },
  { name: "delete_comment", fields: ["author", "permlink"] },
  {
    name: "escrow_approve",
    fields: ["from", "to", "agent", "who", "escrow_id", "approve"],
  },
  {
    name: "escrow_dispute",
    fields: ["from", "to", "agent", "who", "escrow_id"],
  },
  {
    name: "escrow_release",
    fields: [
      "from",
      "to",
      "agent",
      "who",
      "receiver",
      "escrow_id",
      "hbd_amount",
      "hive_amount",
    ],
  },
  {
    name: "escrow_transfer",
    fields: [
      "from",
      "to",
      "agent",
      "escrow_id",
      "hbd_amount",
      "hive_amount",
      "fee",
      "ratification_deadline",
      "escrow_expiration",
      "json_meta",
    ],
  },
  { name: "feed_publish", fields: ["publisher", "exchange_rate"] },
  { name: "limit_order_cancel", fields: ["owner", "orderid"] },
  {
    name: "limit_order_create",
    fields: [
      "owner",
      "orderid",
      "amount_to_sell",
      "min_to_receive",
      "fill_or_kill",
      "expiration",
    ],
  },
  {
    name: "limit_order_create2",
    fields: [
      "owner",
      "orderid",
      "amount_to_sell",
      "exchange_rate",
      "fill_or_kill",
      "expiration",
    ],
  },
  {
    name: "pow",
    fields: ["worker_account", "block_id", "nonce", "work", "props"],
  },
  { name: "pow2", fields: ["work", "new_owner_key", "props"] },
  {
    name: "recover_account",
    fields: [
      "account_to_recover",
      "new_owner_authority",
      "recent_owner_authority",
      "extensions",
    ],
  },
  {
    name: "report_over_production",
    fields: ["reporter", "first_block", "second_block"],
  },
  {
    name: "request_account_recovery",
    fields: [
      "recovery_account",
      "account_to_recover",
      "new_owner_authority",
      "extensions",
    ],
  },
  {
    name: "reset_account",
    fields: ["reset_account", "account_to_reset", "new_owner_authority"],
  },
  {
    name: "set_reset_account",
    fields: ["account", "current_reset_account", "reset_account"],
  },
  {
    name: "set_withdraw_vesting_route",
    fields: ["from_account", "to_account", "percent", "auto_vest"],
  },
  { name: "transfer", fields: ["from", "to", "amount", "memo"] },
  {
    name: "transfer_from_savings",
    fields: ["from", "request_id", "to", "amount", "memo"],
  },
  {
    name: "transfer_to_savings",
    fields: ["amount", "from", "memo", "request_id", "to"],
  },
  { name: "transfer_to_vesting", fields: ["from", "to", "amount"] },
  { name: "vote", fields: ["voter", "author", "permlink", "weight"] },
  { name: "withdraw_vesting", fields: ["account", "vesting_shares"] },
  {
    name: "witness_update",
    fields: ["owner", "url", "block_signing_key", "props", "fee"],
  },
  {
    name: "witness_set_properties",
    fields: ["owner", "props", "extensions"],
  },
  {
    name: "account_update2",
    fields: [
      "account",
      "owner",
      "active",
      "posting",
      "memo_key",
      "json_metadata",
      "posting_json_metadata",
      "extensions",
    ],
  },
  {
    name: "create_proposal",
    fields: [
      "creator",
      "receiver",
      "start_date",
      "end_date",
      "daily_pay",
      "subject",
      "permlink",
      "extensions",
    ],
  },
  {
    name: "update_proposal_votes",
    fields: ["voter", "proposal_ids", "approve", "extensions"],
  },
  {
    name: "remove_proposal",
    fields: ["proposal_owner", "proposal_ids", "extensions"],
  },
  {
    name: "update_proposal",
    fields: [
      "proposal_id",
      "creator",
      "daily_pay",
      "subject",
      "permlink",
      "extensions",
    ],
  },
  {
    name: "collateralized_convert",
    fields: ["owner", "requestid", "amount"],
  },
  {
    name: "recurrent_transfer",
    fields: [
      "from",
      "to",
      "amount",
      "memo",
      "recurrence",
      "executions",
      "extensions",
    ],
  },
] as const;

const OPERAND_LIST = ["==", "!=", ">", ">=", "<", "<="] as const;

const OPERATION_NAMES = [
  "account_create",
  "account_create_with_delegation",
  "account_update",
  "account_witness_proxy",
  "account_witness_vote",
  "cancel_transfer_from_savings",
  "change_recovery_account",
  "claim_reward_balance",
  "claim_account",
  "comment",
  "comment_options",
  "convert",
  "create_claimed_account",
  "custom",
  "custom_binary",
  "custom_json",
  "decline_voting_rights",
  "delegate_vesting_shares",
  "delete_comment",
  "escrow_approve",
  "escrow_dispute",
  "escrow_release",
  "escrow_transfer",
  "feed_publish",
  "limit_order_cancel",
  "limit_order_create",
  "limit_order_create2",
  "pow",
  "pow2",
  "recover_account",
  "report_over_production",
  "request_account_recovery",
  "reset_account",
  "set_reset_account",
  "set_withdraw_vesting_route",
  "transfer",
  "transfer_from_savings",
  "transfer_to_savings",
  "transfer_to_vesting",
  "vote",
  "withdraw_vesting",
  "witness_update",
  "witness_set_properties",
  "account_update2",
  "create_proposal",
  "update_proposal_votes",
  "remove_proposal",
  "update_proposal",
  "collateralized_convert",
  "recurrent_transfer",
] as const;

export type IOperationName = (typeof OPERATION_FIELD_LIST)[number]["name"];
export type IOperand = (typeof OPERAND_LIST)[number];

export const OperationsUtils = {
  OPERAND_LIST,
  OPERATION_FIELD_LIST,
  OPERATION_NAMES,
};
